const GREEN = '#0c4a24'
const GREEN_DEEP = '#062a14'
const GREEN_DARKER = '#04160c'
const GREEN_MID = '#145c30'
const ORANGE = '#f5821f'
const ORANGE_DARK = '#c2590a'
const GOLD = '#f4c430'
const GOLD_DEEP = '#caa000'
const CREAM = '#f6f1e4'
const WHITE = '#ffffff'
const INK = '#0c4a24'

export const EXEC_VARIANTS = [
  {
    slug: '01-classic-green',
    label: 'Classic green duotone (closest to the ULES reference)',
    bg: 'solid',
    colors: {
      bgTop: [GREEN, GREEN_DEEP],
      watermark: 'rgba(255,255,255,0.05)',
      headerText: WHITE,
      headline1: WHITE,
      headline2: GOLD,
      divider: 'rgba(255,255,255,0.25)',
      medallion: [GOLD, ORANGE],
      footerText: GOLD,
      footerSubtext: 'rgba(255,255,255,0.7)',
    },
    panelColor: () => GREEN_MID,
    duotone: () => [GREEN_DEEP, WHITE],
    iconWatermarkAlpha: 0.12,
    nameColor: () => WHITE,
    roleColor: () => GOLD,
    footerIcon: 'events',
    cardRadius: 18,
  },
  {
    slug: '02-alternating-orange-green',
    label: 'Alternating orange/green panels, bolder and more colorful',
    bg: 'solid',
    colors: {
      bgTop: [GREEN, GREEN_DEEP],
      watermark: 'rgba(255,255,255,0.05)',
      headerText: WHITE,
      headline1: WHITE,
      headline2: ORANGE,
      divider: 'rgba(255,255,255,0.25)',
      medallion: [ORANGE, GOLD],
      footerText: WHITE,
      footerSubtext: 'rgba(255,255,255,0.7)',
    },
    panelColor: (col) => (col % 2 === 0 ? GREEN_MID : ORANGE_DARK),
    duotone: () => [GREEN_DEEP, WHITE],
    iconWatermarkAlpha: 0.14,
    nameColor: () => WHITE,
    roleColor: (row, col) => GOLD,
    footerIcon: 'megaphone',
    cardRadius: 18,
  },
  {
    slug: '03-gold-duotone',
    label: 'Warm gold duotone photos, deep green background',
    bg: 'solid',
    colors: {
      bgTop: [GREEN_DEEP, GREEN_DARKER],
      watermark: 'rgba(244,196,48,0.06)',
      headerText: WHITE,
      headline1: GOLD,
      headline2: WHITE,
      divider: 'rgba(244,196,48,0.3)',
      medallion: [GOLD_DEEP, GOLD],
      footerText: GOLD,
      footerSubtext: 'rgba(255,255,255,0.65)',
    },
    panelColor: () => GREEN_MID,
    duotone: () => [GREEN_DEEP, GOLD],
    iconWatermarkAlpha: 0.12,
    nameColor: () => WHITE,
    roleColor: () => GOLD,
    footerIcon: 'grid',
    cardRadius: 18,
  },
  {
    slug: '04-squircle-icon-watermark',
    label: 'Rounded-square cards with a bolder brand-icon watermark',
    bg: 'solid',
    colors: {
      bgTop: [GREEN, GREEN_DEEP],
      watermark: 'rgba(255,255,255,0.05)',
      headerText: WHITE,
      headline1: WHITE,
      headline2: WHITE,
      divider: 'rgba(255,255,255,0.25)',
      medallion: [ORANGE, ORANGE_DARK],
      footerText: WHITE,
      footerSubtext: 'rgba(255,255,255,0.7)',
    },
    panelColor: () => '#0e3d1e',
    duotone: () => [GREEN_DEEP, WHITE],
    iconWatermarkAlpha: 0.22,
    nameColor: () => WHITE,
    roleColor: () => ORANGE,
    footerIcon: 'briefcase',
    cardRadius: 30,
  },
  {
    slug: '05-split-cream',
    label: 'Split green/cream background, dark text on the bottom row',
    bg: 'split',
    splitY: 679,
    colors: {
      bgTop: [GREEN, GREEN_DEEP],
      bgBottom: CREAM,
      watermark: 'rgba(255,255,255,0.05)',
      headerText: WHITE,
      headline1: WHITE,
      headline2: GOLD,
      divider: 'rgba(12,74,36,0.25)',
      medallion: [GOLD, ORANGE],
      footerText: INK,
      footerSubtext: 'rgba(12,74,36,0.6)',
    },
    panelColor: (col, row) => (row === 0 ? GREEN_MID : ORANGE_DARK),
    duotone: () => [GREEN_DEEP, WHITE],
    iconWatermarkAlpha: 0.14,
    nameColor: (row) => (row === 0 ? WHITE : INK),
    roleColor: (row) => (row === 0 ? GOLD : ORANGE_DARK),
    footerIcon: 'grid',
    cardRadius: 18,
  },
]
