export const FLYERS = [
  {
    slug: '01-hub-launch',
    icon: 'grid',
    headline: ['NAMMES HUB', 'IS HERE'],
    subheadline: ['Your entire NAMMES journey,', 'in one app.'],
    bullets: ['Outlines & resources, all levels', 'Timetable, events & opportunities', 'News, awards & Excos directory'],
    cta: 'Visit NAMMES Hub — link in bio',
    seed: 1,
  },
  {
    slug: '02-cgpa-calculator',
    icon: 'calculator',
    headline: ['KNOW YOUR CGPA.', 'INSTANTLY.'],
    subheadline: ['No more spreadsheets or guesswork.'],
    bullets: ['Add courses per semester', 'Auto-calculates your GPA & CGPA', 'Track progress across levels'],
    cta: 'Try it free on NAMMES Hub',
    seed: 2,
  },
  {
    slug: '03-outlines-resources',
    icon: 'book',
    headline: ['EVERY COURSE', 'OUTLINE. ONE PLACE.'],
    headlineFontSize: 78,
    subheadline: ['From 100L to 500L — outlines & resources', 'sorted by level.'],
    bullets: ['Browse by level & course code', 'Download resources instantly', 'Always up to date'],
    cta: 'Find your course outline now',
    seed: 3,
  },
  {
    slug: '04-timetable',
    icon: 'calendar',
    headline: ['NEVER MISS A', 'CLASS AGAIN'],
    subheadline: ['Your full weekly timetable,', 'organized by level.'],
    bullets: ['Full weekly schedule', 'Organized by level', "Today's classes at a glance"],
    cta: 'Check your timetable now',
    seed: 4,
  },
  {
    slug: '05-events-rsvp',
    icon: 'events',
    headline: ["DON'T MISS", "WHAT'S NEXT"],
    subheadline: ['Discover NAMMES events and', 'RSVP in seconds.'],
    bullets: ['See all upcoming events', 'Get event details & location', 'RSVP with one tap'],
    cta: 'Explore events on NAMMES Hub',
    seed: 5,
  },
  {
    slug: '06-opportunities',
    icon: 'briefcase',
    headline: ['INTERNSHIPS.', 'SCHOLARSHIPS. JOBS.'],
    headlineFontSize: 76,
    subheadline: ['Curated opportunities for MME', 'students, in one board.'],
    bullets: ['New opportunities added weekly', 'Filtered for your field', 'Apply before deadlines close'],
    cta: 'Browse opportunities now',
    seed: 6,
  },
  {
    slug: '07-stay-connected',
    icon: 'megaphone',
    headline: ['STAY IN', 'THE LOOP'],
    subheadline: ['Association news, award winners', '& your current Excos.'],
    bullets: ['Association news', 'Award updates', 'Connect with Excos'],
    cta: 'Catch up on NAMMES Hub',
    seed: 7,
  },
]
