// Checks public/ for the optional audio files and writes src/assetManifest.ts, so the video only references files that
// exist (no 404s, no errors when they are missing). Runs automatically before `npm run preview` and the render scripts.
import { existsSync, readdirSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'

const root = join(__dirname, '..')
const FILES = { music: 'music.mp3', voiceover: 'voiceover.mp3' } as const

export function writeAssetManifest() {
  const found: Record<string, boolean> = {}
  for (const [key, file] of Object.entries(FILES)) found[key] = existsSync(join(root, 'public', file))
  const voDir = join(root, 'public', 'vo')
  const clips = existsSync(voDir) ? readdirSync(voDir).filter((f) => f.endsWith('.wav')).map((f) => f.replace('.wav', '')).sort() : []
  const sfxDir = join(root, 'public', 'sfx')
  const sfx = existsSync(sfxDir) ? readdirSync(sfxDir).filter((f) => f.endsWith('.mp3')).map((f) => f.replace('.mp3', '')).sort() : []
  const body = `// AUTO-GENERATED by scripts/assets-manifest.ts. Do not edit by hand.\nexport const HAS_AUDIO = ${JSON.stringify(found, null, 2)} as const\nexport const VO_CLIPS: string[] = ${JSON.stringify(clips)}\nexport const SFX_FILES: string[] = ${JSON.stringify(sfx)}\n`
  writeFileSync(join(root, 'src', 'assetManifest.ts'), body, 'utf8')
  return found
}

if (require.main === module) {
  const found = writeAssetManifest()
  console.log('Optional audio found:', Object.entries(found).map(([k, v]) => `${k}=${v ? 'yes' : 'no'}`).join(' '))
}
