// Writes captions.srt and voiceover-script.md from the timing in src/constants.ts and the text in src/script.ts.
// Run with `npm run docs` (the render scripts run it for you).
import { writeFileSync } from 'node:fs'
import { join } from 'node:path'
import { BEAT_SECONDS, FPS, SCENE_ORDER, SCENE_START, SCENE_TITLES, TOTAL_FRAMES, sceneFrames, sec } from '../src/constants'
import { CAPTIONS } from '../src/captions'
import { VO } from '../src/script'

const root = join(__dirname, '..')

const pad = (n: number, w = 2) => String(n).padStart(w, '0')
function srtTime(frame: number) {
  const ms = Math.round((frame / FPS) * 1000)
  const h = Math.floor(ms / 3600000)
  const m = Math.floor((ms % 3600000) / 60000)
  const s = Math.floor((ms % 60000) / 1000)
  return `${pad(h)}:${pad(m)}:${pad(s)},${pad(ms % 1000, 3)}`
}
function clock(frame: number) {
  const s = Math.round(frame / FPS)
  return `${Math.floor(s / 60)}:${pad(s % 60)}`
}

// captions.srt
const srt = CAPTIONS.map((c, i) => `${i + 1}\n${srtTime(c.start)} --> ${srtTime(c.end)}\n${c.text}\n`).join('\n')
writeFileSync(join(root, 'captions.srt'), srt, 'utf8')

// voiceover-script.md
const warnings: string[] = []
const lines: string[] = []
lines.push('# NAMMES Hub explainer: voiceover script')
lines.push('')
lines.push(`Total length: **${clock(TOTAL_FRAMES)}** (${(TOTAL_FRAMES / FPS).toFixed(1)} s). Generated from \`src/constants.ts\` (timing) and \`src/script.ts\` (words). Do not edit this file by hand; change those two files and run \`npm run docs\`.`)
lines.push('')
lines.push('How to use it: record (or feed to a text-to-speech voice) one line per beat, trim each clip to its duration, and lay them on a timeline at the start times below. Or record one take at a fun, quick, friendly pace and export a single `voiceover.mp3` into `public/`. The video will play it and duck the music under it. Voice direction: warm, playful, Lagos campus energy. Light slang is fine, never forced.')
lines.push('')
for (const scene of SCENE_ORDER) {
  lines.push(`## ${SCENE_TITLES[scene]}  (${clock(SCENE_START[scene])} to ${clock(SCENE_START[scene] + sceneFrames(scene))}, ${(sceneFrames(scene) / FPS).toFixed(1)} s)`)
  lines.push('')
  lines.push('| Starts | Beat | Duration | Line |')
  lines.push('| --- | --- | --- | --- |')
  let t = SCENE_START[scene]
  for (const [beat, seconds] of Object.entries(BEAT_SECONDS[scene])) {
    const text = (VO[scene] as Record<string, string>)[beat]
    const words = text.split(/\s+/).length
    const wps = words / (seconds as number)
    if (wps > 2.9) warnings.push(`${scene}/${beat}: ${words} words in ${seconds}s (${wps.toFixed(1)} words/s), likely too fast to read`)
    lines.push(`| ${clock(t)} | ${beat} | ${seconds}s | ${text} |`)
    t += sec(seconds as number)
  }
  lines.push('')
}
writeFileSync(join(root, 'voiceover-script.md'), lines.join('\n'), 'utf8')

console.log(`Wrote captions.srt (${CAPTIONS.length} captions) and voiceover-script.md. Total ${clock(TOTAL_FRAMES)}.`)
if (warnings.length) console.warn('Pacing warnings:\n - ' + warnings.join('\n - '))
