import { describe, it, expect } from 'vitest'
import { writeFileSync, existsSync } from 'node:fs'
import { renderToStaticMarkup } from 'react-dom/server'
import { createElement } from 'react'
import Character from '../src/components/quiz/Character.jsx'
import { AVATAR_COUNT } from '../src/data/quizCharacters.js'

// The result cards are drawn on the server, where Node cannot load a .jsx file — Vercel's Node runtime fails the whole
// function with FUNCTION_INVOCATION_FAILED rather than degrading. So the characters' markup is generated here, from
// the component itself, into a plain .js module the server can import.
//
// The component stays the single source of truth: this test renders both and fails if they ever disagree, so
// changing a character without re-running the generator is a build failure rather than a silent drift.
//
//   npm run cards:characters   regenerates the module
//   npm test                    proves the module still matches the component

const TARGET = 'api/_lib/quizCharacterMarkup.js'
const MOODS = ['idle', 'happy', 'dance', 'sad', 'wave']

// The classes the browser's stylesheet animates. They mean nothing to the renderer and would only bloat the file.
function stripClasses(svg) {
  return svg.replace(/\sclass="[^"]*"/g, '')
}

function fromComponent(id, mood) {
  return stripClasses(renderToStaticMarkup(createElement(Character, { id, mood })))
}

function build() {
  const entries = {}
  for (const mood of MOODS) {
    for (let id = 0; id < AVATAR_COUNT; id++) entries[`${id}:${mood}`] = fromComponent(id, mood)
  }
  return entries
}

const SOURCE = `// Generated by scripts/quizCharacterMarkup.test.js — do not edit.
// The 50 quiz characters' SVG markup, as plain data, for the result cards. Character.jsx stays the source of truth;
// the test that writes this file also fails if the two ever disagree, so never hand-edit it here.
//
// It exists only because the cards are drawn on the server and Node cannot load a .jsx file. Regenerate with:
//   npm run cards:characters

export const CARD_MOODS = ${JSON.stringify(MOODS)}

export const CHARACTER_MARKUP = ${JSON.stringify(build(), null, 0)}

export function characterMarkup(id, mood = 'happy') {
  return CHARACTER_MARKUP[\`\${id}:\${mood}\`] ?? CHARACTER_MARKUP['0:happy']
}
`

const entries = build()

// The write happens as the module loads, before any assertion runs, so `npm run cards:characters` leaves the file
// correct and then passes, while a plain `npm test` never writes and only checks.
if (process.env.REGEN_CARD_CHARACTERS === '1') writeFileSync(TARGET, SOURCE)

describe('the generated character markup', () => {

  it(`covers all ${AVATAR_COUNT} characters and ${MOODS.length} moods`, () => {
    expect(Object.keys(entries)).toHaveLength(AVATAR_COUNT * MOODS.length)
  })

  it('matches Character.jsx exactly', async () => {
    if (!existsSync(TARGET)) throw new Error(`${TARGET} is missing. Run: npm run cards:characters`)
    const { CHARACTER_MARKUP: stored } = await import('../api/_lib/quizCharacterMarkup.js')
    const drifted = Object.keys(entries).filter((key) => stored[key] !== entries[key])
    expect(
      drifted,
      `${drifted.length} character(s) no longer match Character.jsx. Run: npm run cards:characters`,
    ).toEqual([])
  })
})