// AUTO-GENERATED by scripts/assets-manifest.ts. Do not edit by hand.
export const HAS_AUDIO = {
  "music": true,
  "voiceover": false
} as const
export const VO_CLIPS: string[] = ["academics-cgpa","academics-curriculum","academics-detail","academics-outlines","academics-resources","academics-timetable","behind-dashboard","behind-form","behind-host","behind-news","behind-season","close-built","close-endcard","close-excos","cold-chat","cold-deadline","cold-logo","cold-photo","cold-stamp","community-awards","community-events","community-forms","community-news","community-opportunities","meet-account","meet-home","meet-map","quiz-bracket","quiz-champion","quiz-duel","quiz-lobby","quiz-powers","quiz-question","quiz-reveal","quiz-share"]
export const SFX_FILES: string[] = ["chime","click","ding","error","fanfare","impact","ping","pop","rise","scan","shutter","stamp","swish","tick","type","whoosh"]
